/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.Random;

public class App {

    public static void main(String[] args) {

        Random r = new Random();

        Carro f = new Carro();
        Carro g = new Carro();

        f.definirModelo("Fusca");
        g.definirModelo("Gol");

        f.definirVelocidadeAtual(20);
        g.definirVelocidadeAtual(90);

        System.out.println(f.obterModelo() + " está a  " + f.obterVelocidadeAtual());
        System.out.println(g.obterModelo() + " está a  " + g.obterVelocidadeAtual());


    }
}
